[
  {"lib/symphony_elixir/agent_runner.ex", "Invalid type specification for function run."},
  {"lib/symphony_elixir/agent_runner.ex", "Function run/1 has no local return."},
  {"lib/symphony_elixir/agent_runner.ex", "Function run/2 has no local return."},
  {"lib/symphony_elixir/agent_runner.ex", "Function run/3 has no local return."},
  {"lib/symphony_elixir/agent_runner.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir/agent_runner.ex", "Function codex_message_handler/2 will never be called."},
  {"lib/symphony_elixir/agent_runner.ex", "Function send_codex_update/3 will never be called."},
  {"lib/symphony_elixir/agent_runner.ex", "Function do_run_codex_turns/8 will never be called."},
  {"lib/symphony_elixir/codex/app_server.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir/codex/app_server.ex", "Function send_initialize/1 will never be called."},
  {"lib/symphony_elixir/codex/app_server.ex", "Function do_start_session/3 will never be called."},
  {"lib/symphony_elixir/codex/app_server.ex", "Function start_thread/3 will never be called."},
  {"lib/symphony_elixir/codex/app_server.ex",
   "The pattern variable __normalized@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/app_server.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/codex/app_server.ex",
   "Type mismatch in call with opaque term in expand_shell_command_candidates."},
  {"lib/symphony_elixir/codex/app_server.ex", "Type mismatch in call without opaque term in put."},
  {"lib/symphony_elixir/codex/dynamic_tool.ex",
   "The pattern variable _reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/config/model_routing.ex", "The pattern can never match the type true."},
  {"lib/symphony_elixir/orchestrator.ex", "The created anonymous function has no local return."},
  {"lib/symphony_elixir/orchestrator.ex",
   "The pattern variable __running_entry@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator.ex",
   "The pattern pattern <__running_entry@1, __updated_running_entry@1, __update@1, __token_delta@1> can never match the type, because it is covered by previous clauses."}
]
